boot.o: boot.S multiboot.h x86_desc.h types.h
Execute_Haltasm.o: Execute_Haltasm.S x86_desc.h types.h
intrexce.o: intrexce.S x86_desc.h types.h
Syscall_handler.o: Syscall_handler.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
e391exception.o: e391exception.c lib.h types.h e391exception.h
e391keyboard.o: e391keyboard.c lib.h types.h e391synchronize.h i8259.h \
  intrexcenum.h e391keyboard.h
e391terminal.o: e391terminal.c types.h e391terminal.h e391keyboard.h \
  lib.h
Execute_Halt.o: Execute_Halt.c Syscalls.h types.h PCB.h fileSystem.h \
  lib.h rtc.h e391terminal.h e391keyboard.h x86_page.h x86_desc.h
fileSystem.o: fileSystem.c fileSystem.h lib.h types.h Syscalls.h PCB.h \
  rtc.h e391terminal.h e391keyboard.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h x86_page.h idt.h lib.h \
  fileSystem.h i8259.h debug.h tests.h e391keyboard.h intrexcenum.h rtc.h \
  Syscalls.h PCB.h e391terminal.h
lib.o: lib.c lib.h types.h x86_page.h
PCB.o: PCB.c PCB.h types.h fileSystem.h lib.h
rtc.o: rtc.c lib.h types.h rtc.h e391synchronize.h i8259.h intrexcenum.h
Syscalls.o: Syscalls.c Syscalls.h types.h PCB.h fileSystem.h lib.h rtc.h \
  e391terminal.h e391keyboard.h
tests.o: tests.c tests.h x86_desc.h types.h x86_page.h fileSystem.h lib.h \
  Syscalls.h PCB.h rtc.h e391terminal.h e391keyboard.h
x86_page.o: x86_page.c x86_desc.h types.h lib.h x86_page.h
